/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory_management_system;

import javax.swing.JOptionPane;

/**
 *
 * @author Mariz
 */
public class PH_LOADINGSCREEN extends javax.swing.JFrame {

    /**
     * Creates new form PH_LOGIN
     */
    public PH_LOADINGSCREEN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pH_LOGINPAGE1 = new inventory_management_system.PH_LOGINPAGE();
        BACKGROUNDPANEL = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        title3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        loading = new javax.swing.JLabel();
        loadingvalue = new javax.swing.JLabel();
        backgroundImage = new javax.swing.JLabel();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pharmacy (1).png"))); // NOI18N
        jLabel4.setText("    ");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("GungsuhChe", 0, 40)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("D&J|PHARMACY INVENTORY MANAGEMENT SYSTEM");

        jLabel7.setFont(new java.awt.Font("Narkisim", 0, 14)); // NOI18N
        jLabel7.setText("Barangay Villareal, Bayawan City, Negros Oriental, Philippines 6114");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        BACKGROUNDPANEL.setBackground(new java.awt.Color(0, 204, 255));
        BACKGROUNDPANEL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logoSYSTEM (5).png"))); // NOI18N
        BACKGROUNDPANEL.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, 330));

        title3.setBackground(new java.awt.Color(0, 0, 0));
        title3.setFont(new java.awt.Font("Mistral", 1, 48)); // NOI18N
        title3.setForeground(new java.awt.Color(255, 255, 255));
        title3.setText("Management System");
        BACKGROUNDPANEL.add(title3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, -1, -1));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 72)); // NOI18N
        jLabel1.setText("PHARMACY");
        BACKGROUNDPANEL.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, -1));

        jProgressBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BACKGROUNDPANEL.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 890, 30));

        loading.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        loading.setForeground(new java.awt.Color(255, 255, 255));
        loading.setText("loading...");
        BACKGROUNDPANEL.add(loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, -1, -1));

        loadingvalue.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        loadingvalue.setForeground(new java.awt.Color(255, 255, 255));
        loadingvalue.setText("0%");
        BACKGROUNDPANEL.add(loadingvalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 600, -1, -1));

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/top-view-variety-medicine-tablets.jpg"))); // NOI18N
        backgroundImage.setText("jLabel3");
        backgroundImage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BACKGROUNDPANEL.add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 900, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BACKGROUNDPANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BACKGROUNDPANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
   
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    
    
    
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(PH_LOADINGSCREEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    /* Create and display the form */
    PH_LOADINGSCREEN LS = new PH_LOADINGSCREEN();
    LS.setVisible(true);

    try {
        for (int i = 0; i <= 100; i++) {
            Thread.sleep(35);
            LS.loadingvalue.setText(i + "%");

            if (i == 10) {
                LS.loading.setText("Turning on modules...");
            }
            if (i == 20) {
                LS.loading.setText("Loading Modules...");
            }
            if (i == 30) {
                LS.loading.setText("Connecting to Database...");
            }
            if (i == 40) {
                LS.loading.setText("Connection Successful...");
            }
            if (i == 50) {
                LS.loading.setText("Launching Application...");
            }
            LS.jProgressBar1.setValue(i);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
     LS.setVisible(false);  

    java.awt.EventQueue.invokeLater(() -> {
        PH_LOGINPAGE LP = new PH_LOGINPAGE();
        LP.setVisible(true);
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BACKGROUNDPANEL;
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel loading;
    private javax.swing.JLabel loadingvalue;
    private inventory_management_system.PH_LOGINPAGE pH_LOGINPAGE1;
    private javax.swing.JLabel title3;
    // End of variables declaration//GEN-END:variables
}
